name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17.3.0
        uses: actions/setup-node@v2
        with:
          node-version: 17.3.0
          cache: "npm"
      - run: npm ci
      - run: npm test
